### ISSUE TITLE
Allowing all mime types

### ISSUE THREAD

**Issue by andreybleme** [aivis/PHP-file-upload-class#10]
If i want to allow all the mime types, can i just don't put the line that checks the mime types?
Like this:

`//set allowed mime types - delete this line for allow all mime types
    //$upload->set_allowed_mime_types(array('application/pdf'));`

Or i need to allow a * in instead of puting the mime type?
Like this:
`//set allowed mime types - puting a "*" instead of a mime type
    $upload->set_allowed_mime_types(array('application/ * '));`

Thanks for the awesome upload class !

**Comment by JulioSimon** [comment]
If you want to allow all mime types, do not set any allowed mime types in the mimes array. The callback that checks for mimes only validate if the array is not empty.

You can proceed in this way to upload a file allowing all mime types but with file size validation:

```php
if (!empty($_FILES['test'])) {

    $upload = Upload::factory('important/files');
    $upload->file($_FILES['test']);

    //set max. file size (in mb)
    $upload->set_max_file_size(1);

    $results = $upload->upload();

    var_dump($results);

}
```

**Comment by andreybleme** [comment]
Hm, got it! Thanks :+1:
