### ISSUE TITLE
Fatal error: Class 'finfo' not found

### ISSUE THREAD

**Issue by arammarm** [aivis/PHP-file-upload-class#13]
I tried from test.php but its giving this error

**Comment by ahsanic** [comment]
Hi, I am getting the same error!

Fatal error: Class 'finfo' not found in C:\xampp\htdocs\zf\fileupload\upload.php on line 161

**Comment by aivis** [comment]
@ahsanic @arammarm you have to install following PHP extension: http://php.net/manual/en/book.fileinfo.php

as it says in the documentation:
> You need to install (or enable in php.ini) PHP "file info" extension.

Probably useful links:
- http://stackoverflow.com/questions/3579072/php-fileinfo-is-undefined-function
- http://stackoverflow.com/questions/24850136/i-have-ext-fileinfo-but-composer-says-it-is-missing
