### ISSUE TITLE
problem with upload array of file

### ISSUE THREAD

**Issue by alikarimii** [aivis/PHP-file-upload-class#18]
hi 
i want upload array like this
`Array
(
    [0] => Array
        (
            [name] => 7feb99f684d5d44eceb8084247188bc5.jpg
            [type] => image/jpeg
            [tmp_name] => C:\wamp64\tmp\php2506.tmp
            [error] => 0
            [size] => 276309
        )

    [1] => Array
        (
            [name] => 6ee8368da2517a4b9802506695231697.jpg
            [type] => image/jpeg
            [tmp_name] => C:\wamp64\tmp\php2507.tmp
            [error] => 0
            [size] => 268148
        )

)
`
what to do?

**Comment by aivis** [comment]
One of the options would be to:

```php
foreach($_FILES as $file)
{
	$upload = Upload::factory('important/files');
	$upload->file($file);
	
	$results = $upload->upload();
	var_dump($results);
}
//...
```

**Comment by alikarimii** [comment]
thanks
