### ISSUE TITLE
upload two file in separate destination

### ISSUE THREAD

**Issue by alikarimii** [aivis/PHP-file-upload-class#19]
i have an array 
`array
        'first=>
             array
                     name =>'a'
                      .....
          sec =>
            array
                    name =>'b''`

i want use Upload class in another class and upload first to first/path and sec to sec/path
please help .how?
thanks

**Comment by strider72** [comment]
Sounds like you just need a for...each loop.

**Comment by aivis** [comment]
Yes, Just create a new instance of uploader for each file.
